games_app/urls.py
from django.conf.urls import patterns, url

from games_app import views

urlpatterns = patterns('',
    url(r'^$', views.games_list, name='games_latest', kwargs={'ev':None}),
    url(r'^(?P<ev>\d+)/$', views.games_list, name='games'),

    url(r'^req/(?P<ev>\d+)/$', views.games_req, name='games_req'),
    url(r'^req/(?P<ev>\d+)/d/$', views.games_req, name='games_req_delete'),
    url(r'^req/(?P<ev>\d+)/u/$', views.games_req, name='games_req_update'),

    url(r'^events/$', views.event_list, name='events'),
    url(r'^events/c/$', views.CreateEvent.as_view(), name='event_create'),
    url(r'^events/u(?P<pk>\d+)/$', views.UpdateEvent.as_view(), name='event_update'),
    url(r'^events/d/(?P<pk>\d+)/$', views.DeleteEvent.as_view(), name='event_delete'),
)

games_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^games/', include('games_app.urls')),
    # Examples:
    # url(r'^$', 'games_db.views.home', name='home'),
    # url(r'^games_db/', include('games_db.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

#urlpatterns += staticfiles_urlpatterns()

games_app/models.py
from django.db import models


class Event(models.Model):
    name = models.CharField(max_length=30, verbose_name='Event')
    when = models.DateField()
    added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '<Event: %s>' % self.name


class Game(models.Model):
    event = models.ForeignKey(Event)
    name = models.CharField(max_length=50)
    bringer = models.CharField(max_length=20, blank=True)
    requester = models.CharField(max_length=20, blank=True)
    added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "<Game: %s, %s>" % (self.name, self.bringer)

    class Meta:
        unique_together = (('name','event'),)


class Comment(models.Model):
    game = models.ForeignKey(Game)
    comm_txt = models.CharField(max_length=80)

    def __unicode__(self):
        return "<GameComment: %s, %s>" % (self.ame, self.comm_txt)


class Player(models.Model):
    game = models.ForeignKey(Game)
    event = models.ForeignKey(Event)
    who = models.CharField(max_length=20)

games_app/forms.py
from django import forms
from django.forms.formsets import formset_factory
from django.contrib.admin import widgets
from games_app.models import Event

class EventForm(forms.ModelForm):
    class Meta:
        model = Event

class GameReqForm(forms.Form):
    game = forms.CharField()
    comment = forms.CharField(required=False)
    bringing = forms.BooleanField(required=False)

GameReqFormset = formset_factory(GameReqForm, extra=9)

games_app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_tables2 import RequestConfig, SingleTableMixin

from games_app.models import Game, Event
from games_app.tables import EventTable, RequestedGamesTable
from games_app.tables import ConfirmedGamesTable
from games_app.forms import EventForm, GameReqFormset 

import json

def games_list(request, ev=None):
    if ev is not None:
        event = get_object_or_404(Event, pk=ev)
    else:
        event = Event.objects.order_by('added')[0]
    events = Event.objects.order_by('added')
    games = Game.objects.all().filter(event__exact=event)
    games_requested = games.filter(bringer__exact='')
    games_confirmed = games.exclude(bringer__exact='')
    template = 'games_app/games.html'
    req_table = RequestedGamesTable(games_requested, prefix="req-")
    conf_table = ConfirmedGamesTable(games_confirmed, prefix="conf-")
    RequestConfig(request).configure(req_table)
    RequestConfig(request).configure(conf_table)
   
    return render(request, template, {'events': events,
                                      'event': event,
                                      'req_table': req_table,
                                      'conf_table': conf_table})

def event_list(request):
    table = EventTable(Event.objects.all())
    table.paginate(page=request.GET.get('page',1), per_page=6)
    RequestConfig(request, paginate={'per_page':6}).configure(table)

    event_form = EventForm()

    return render(request, 'games_app/events.html', {'events':table,
                                                      'form':event_form}) 

class CreateEvent(CreateView):
    model = Event
    success_url = reverse_lazy('events')

class UpdateEvent(UpdateView):
    model = Event
    success_url = reverse_lazy('events')
    template_name = "games_app/event_edit.html"

class DeleteEvent(DeleteView):
    model = Event
    success_url = reverse_lazy('events')
    template_name = "games_app/event_confirm_delete.html"

def games_req(request, ev):
    event = get_object_or_404(Event, pk=ev) 
    if request.method == 'POST':
        formset = GameReqFormset(request.POST, request.FILES)
        for game_req in formset:
            game_req.is_valid()
            game = game_req.cleaned_data.get('game')
            comment = game_req.cleaned_data.get('comment')
            bringing = game_req.cleaned_data.get('bringing')
            if game:
                game_entry = Game(event=event, name=game, bringer='pflarr', requester='somebody')
                game_entry.save()
    else:
        formset = GameReqFormset()

    return render(request, 'games_app/req.html', {'event':event, 'formset':formset})

games_app/templates/games_app/event_confirm_delete.html
{% block title %}{{ form_title }} {% endblock %}
<p>
{% block body_content %}
<h3>
Delete event <b>{{ object.name }}</b>?
</h3>
<form action="" method="post">
{% csrf_token %}
<input type="submit" 
    value="Yes"
    name="delete" />
</form>
{% endblock %}

games_app/templates/games_app/event_edit.html
{% load render_table from django_tables2 %}
<!doctype html>

<html>
<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css">
</head>
<body>
    <form action="{% url 'event_update' object.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

games_app/templates/games_app/events.html
{% load render_table from django_tables2 %}
<!doctype html>

<html>
<head>
    <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <script type="text/javascript">
        $(function() {
            $( "#id_when" ).datepicker();
        }); 
    </script>
</head>
<body>
    {% render_table events %}
    <form action="{% url 'event_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

games_app/templates/games_app/games.html
{% load render_table from django_tables2 %}
<!doctype html>

<html>
<head>
    <script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}django_tables2/themes/paleblue/css/screen.css">
    <script type="text/javascript">
    function select_event() {
        document.location.href = $('#event_select option:selected').val();
    }
    </script>
</head>
<body>
    <div id="event_select">
        <select name="cur_event" onchange="select_event()">
          {% for ev in events %}
            <option value="{% url 'games' ev.pk %}" {% if ev.pk == event.pk %}selected{%endif%}>{{ ev.name }}</option>
          {% endfor %}
        </select>
        <a href="{% url 'events' %}">Manage Events</a>
    </div>
    <p>
        {% render_table req_table %}
    </p>
    <a href="{% url 'games_req' event.id %}">Add Requests</a>
    <p>
        {% render_table conf_table %}
    </p>
</body>
</html>

games_app/templates/games_app/index.html
<form action="{% url 'games_app:add_req' event.id %}" method="post">
{% csrf_token %}
<select name="event_name">
{% for ev in events %}
    <option value="{{ev.id}}">{{ev.name}}</option>
{% endfor %}
</select>
<input type="text" name="game" id="game">
<input type="text" name="requester" id="requester">
<input type="text" name="comment" id="comment">
</form>

{% if games_list %}
    <ul>
    {% for game in games_list %}
        <li>{{game.game}}, {{game.requester}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No games in db.</p>
{% endif %}

games_app/templates/games_app/req.html
<!doctype html>

<html>
<head>
<script type="text/javascript" src="http://code.jquery.com/jquery-2.1.0.min.js"></script>
</head>
<body>
    <form action="{% url 'games_req' event.pk %}" method="POST">
    {% csrf_token %}

    {{ formset.non_form_errors.as_ul }}
    {{ formset.management_form }}
    <table id="formset" class="form">
    {% for form in formset.forms %}
      {% if forloop.first %}
      <thead><tr>
        {% for field in form.visible_fields %}
        <th>{{ field.label|capfirst }}</th>
        {% endfor %}
      </tr></thead>
      {% endif %}
      <tr class="{% cycle row1,row2 %}">
      {% for field in form.visible_fields %}
        <td>
        {# Include the hidden fields in the form #}
        {% if forloop.first %}
          {% for hidden in form.hidden_fields %}
          {{ hidden }}
          {% endfor %}
        {% endif %}
          {{ field.errors.as_ul }}
          {{ field }}
        </td>
      {% endfor %}
      </tr>
    {% endfor %}
    </table>


    <input type="submit" value="Submit">
    </form>
</body>
</html>

games_app/templates/games_tracker/games_list.html
<form action="{% url 'games_tracker:game_request' gametb.id %}" method="post">
{% csrf_token %}
<select name="event_name">
{% for event in events %}
    <option value="{% event.id %}">{% event.name %}</option>
{% endfor %}
</select>
<input type="text" name="game" id="game">
<input type="text" name="requester" id="requester">
<input type="text" name="comment" id="comment">
</form>

{% if games_list %}
    <ul>
    {% for game in games_list %}
        <li>{{game.game}}, {{game.requester}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No games in db.</p>
{% endif %}